<?php
/**
 * @file
 * CloudFRont Path invalidate install file.
 */

/**
 * Implements hook_uninstall().
 */
function cloudfront_path_invalidate_uninstall() {
  variable_del('cloudfront_path_invalidate_invalidation_url');
  variable_del('cloudfront_path_invalidate_distribution');
  variable_del('cloudfront_path_invalidate_access');
  variable_del('cloudfront_path_invalidate_secret');
  variable_del('cloudfront_path_invalidate_homapage');
  variable_del('cloudfront_path_invalidate_host_provider');
}
